# -*- coding: utf-8 -*-
import datetime as dt

DEPORTE = (
    ('Futbol', 'Futbol'),
    ('Basquet', 'Basquet'),
    ('Paddle', 'Paddle'),
    ('Tenis', 'Tenis'))

FACTURACION = (
    ('CBU', 'CBU'),
    ('Mercado Pago', 'Mercado Pago'))

SUPERFICIE = (
    ('Cesped Natural', 'Cesped Natural'),
    ('Cesped Sintetico', 'Cesped Sintetico'),
    ('Polvo de Ladrillo', 'Polvo de Ladrillo'),
    ('Cemento', 'Cemento'),
    ('Cancha rapida', 'Cancha rapida'),
    ('Parquet', 'Parquet'),
    ('Otros', 'Otros'))

ESTADOS = (
    ('pendiente', 'pendiente'),
    ('acreditada', 'acreditada'),
    ('vencida', 'vencida'),
    ('cancelada', 'cancelada'),
    ('reintegrada', 'reintegrada'))

RETIRO_ESTADO = (
    ("A liquidar", 'A liquidar'),
    ("Pagado", 'Pagado'),
    ("A Revisar", 'A revisar'),)


# Time generator
    # def f(i):
    #     return str(i)+':00Hs a '+str(i+1)+':00Hs'
    # lst = [(f(i),f(i)) for i in range(0,24)]


TIME_CHOICES = (
    ("0:00Hs a 1:00Hs", '0:00Hs a 1:00Hs'),
    ("1:00Hs a 2:00Hs", '1:00Hs a 2:00Hs'),
    ("2:00Hs a 3:00Hs", '2:00Hs a 3:00Hs'),
    ("3:00Hs a 4:00Hs", '3:00Hs a 4:00Hs'),
    ("4:00Hs a 5:00Hs", '4:00Hs a 5:00Hs'),
    ("5:00Hs a 6:00Hs", '5:00Hs a 6:00Hs'),
    ("6:00Hs a 7:00Hs", '6:00Hs a 7:00Hs'),
    ("7:00Hs a 8:00Hs", '7:00Hs a 8:00Hs'),
    ("8:00Hs a 9:00Hs", '8:00Hs a 9:00Hs'),
    ("9:00Hs a 10:00Hs", '9:00Hs a 10:00Hs'),
    ("10:00Hs a 11:00Hs", '10:00Hs a 11:00Hs'),
    ("11:00Hs a 12:00Hs", '11:00Hs a 12:00Hs'),
    ("12:00Hs a 13:00Hs", '12:00Hs a 13:00Hs'),
    ("13:00Hs a 14:00Hs", '13:00Hs a 14:00Hs'),
    ("14:00Hs a 15:00Hs", '14:00Hs a 15:00Hs'),
    ("15:00Hs a 16:00Hs", '15:00Hs a 16:00Hs'),
    ("16:00Hs a 17:00Hs", '16:00Hs a 17:00Hs'),
    ("17:00Hs a 18:00Hs", '17:00Hs a 18:00Hs'),
    ("18:00Hs a 19:00Hs", '18:00Hs a 19:00Hs'),
    ("19:00Hs a 20:00Hs", '19:00Hs a 20:00Hs'),
    ("20:00Hs a 21:00Hs", '20:00Hs a 21:00Hs'),
    ("21:00Hs a 22:00Hs", '21:00Hs a 22:00Hs'),
    ("22:00Hs a 23:00Hs", '22:00Hs a 23:00Hs'),
    ("23:00Hs a 24:00Hs", '23:00Hs a 24:00Hs'))


HOUR_CHOICES = (("00:00", '00:00'),
                ('01:00', '01:00'),
                ("02:00", '02:00'),
                ("03:00", '03:00'),
                ("04:00", '04:00'),
                ("05:00", '05:00'),
                ("06:00", '06:00'),
                ("07:00", '07:00'),
                ("08:00", '08:00'),
                ("09:00", '09:00'),
                ("10:00", '10:00'),
                ("11:00", '11:00'),
                ("12:00", '12:00'),
                ("13:00", '13:00'),
                ("14:00", '14:00'),
                ("15:00", '15:00'),
                ("16:00", '16:00'),
                ("17:00", '17:00'),
                ("18:00", '18:00'),
                ("19:00", '19:00'),
                ("20:00", '20:00'),
                ("21:00", '21:00'),
                ("22:00", '22:00'),
                ("23:00", '23:00'),)


CHOICES_FOR_PROVINCE_FILTER = [
    ('', 'Por favor seleccione una provincia'),
]

PROVINCE_CHOICES = (
    ('B', 'Buenos Aires'), 
    ('K', 'Catamarca'), 
    ('H', 'Chaco'), 
    ('U', 'Chubut'), 
    ('C', 'Capital Federal'),
    ('GBA', 'Buenos Aires - GBA'), 
    ('X', 'Córdoba'), 
    ('W', 'Corrientes'), 
    ('E', 'Entre Ríos'), 
    ('P', 'Formosa'), 
    ('Y', 'Jujuy'), 
    ('L', 'La Pampa'), 
    ('F', 'La Rioja'), 
    ('M', 'Mendoza'), 
    ('N', 'Misiones'), 
    ('Q', 'Neuquén'), 
    ('R', 'Río Negro'), 
    ('A', 'Salta'), 
    ('J', 'San Juan'), 
    ('D', 'San Luis'), 
    ('Z', 'Santa Cruz'), 
    ('S', 'Santa Fe'), 
    ('G', 'Santiago del Estero'), 
    ('V', 'Tierra del Fuego, Antártida e Islas del Atlántico Sur'), 
    ('T', 'Tucumán')
)

CHOICES_FOR_PROVINCE_FILTER.extend(list(PROVINCE_CHOICES))

PAISES_CHOICES = (
    ('AFG', 'Afganistan'),
    ('ALB', 'Albania'),
    ('DEU', 'Alemania'),
    ('DZA', 'Algeria'),
    ('AND', 'Andorra'),
    ('AGO', 'Angola'),
    ('AIA', 'Anguila'),
    ('ATA', 'Antartida'),
    ('ATG', 'Antigua y Barbuda'),
    ('ANT', 'Antillas Neerlandesas'),
    ('SAU', 'Arabia Saudita'),
    ('ARG', 'Argentina'),
    ('ARM', 'Armenia'),
    ('ABW', 'Aruba'),
    ('AUS', 'Australia'),
    ('AUT', 'Austria'),
    ('AZE', 'Azerbayan'),
    ('BEL', 'Belgica'),
    ('BHS', 'Bahamas'),
    ('BHR', 'Bahrein'),
    ('BGD', 'Bangladesh'),
    ('BRB', 'Barbados'),
    ('BLZ', 'Belice'),
    ('BEN', 'Benadn'),
    ('BTN', 'Bhutan'),
    ('BLR', 'Bielorrusia'),
    ('MMR', 'Birmania'),
    ('BOL', 'Bolivia'),
    ('BIH', 'Bosnia y Herzegovina'),
    ('BWA', 'Botsuana'),
    ('BRA', 'Brasil'),
    ('BRN', 'Brunei'),
    ('BGR', 'Bulgaria'),
    ('BFA', 'Burkina Faso'),
    ('BDI', 'Burundi'),
    ('CPV', 'Cabo Verde'),
    ('KHM', 'Camboya'),
    ('CMR', 'Camerun'),
    ('CAN', 'Canada'),
    ('TCD', 'Chad'),
    ('CHL', 'Chile'),
    ('CHN', 'China'),
    ('CYP', 'Chipre'),
    ('VAT', 'Ciudad del Vaticano'),
    ('COL', 'Colombia'),
    ('COM', 'Comoras'),
    ('COG', 'Congo'),
    ('COD', 'Congo'),
    ('PRK', 'Corea del Norte'),
    ('KOR', 'Corea del Sur'),
    ('CIV', 'Costa de Marfil'),
    ('CRI', 'Costa Rica'),
    ('HRV', 'Croacia'),
    ('CUB', 'Cuba'),
    ('DNK', 'Dinamarca'),
    ('DMA', 'Dominica'),
    ('ECU', 'Ecuador'),
    ('EGY', 'Egipto'),
    ('SLV', 'El Salvador'),
    ('ARE', 'Emiratos Arabes Unidos'),
    ('ERI', 'Eritrea'),
    ('SVK', 'Eslovaquia'),
    ('SVN', 'Eslovenia'),
    ('ESP', 'España'),
    ('USA', 'Estados Unidos de America'),
    ('EST', 'Estonia'),
    ('ETH', 'Etiopia'),
    ('PHL', 'Filipinas'),
    ('FIN', 'Finlandia'),
    ('FJI', 'Fiyi'),
    ('FRA', 'Francia'),
    ('GAB', 'Gabon'),
    ('GMB', 'Gambia'),
    ('GEO', 'Georgia'),
    ('GHA', 'Ghana'),
    ('GIB', 'Gibraltar'),
    ('GRD', 'Granada'),
    ('GRC', 'Grecia'),
    ('GRL', 'Groenlandia'),
    ('GLP', 'Guadalupe'),
    ('GUM', 'Guam'),
    ('GTM', 'Guatemala'),
    ('GUF', 'Guayana Francesa'),
    ('GGY', 'Guernsey'),
    ('GIN', 'Guinea'),
    ('GNQ', 'Guinea Ecuatorial'),
    ('GNB', 'Guinea-Bissau'),
    ('GUY', 'Guyana'),
    ('HTI', 'Haiti'),
    ('HND', 'Honduras'),
    ('HKG', 'Hong kong'),
    ('HUN', 'Hungría'),
    ('IND', 'India'),
    ('IDN', 'Indonesia'),
    ('IRN', 'Irán'),
    ('IRQ', 'Irak'),
    ('IRL', 'Irlanda'),
    ('BVT', 'Isla Bouvet'),
    ('IMN', 'Isla de Man'),
    ('CXR', 'Isla de Navidad'),
    ('NFK', 'Isla Norfolk'),
    ('ISL', 'Islandia'),
    ('BMU', 'Islas Bermudas'),
    ('CYM', 'Islas Caimán'),
    ('CCK', 'Islas Cocos (Keeling)'),
    ('COK', 'Islas Cook'),
    ('ALA', 'Islas de Aland'),
    ('FRO', 'Islas Feroe'),
    ('SGS', 'Islas Georgias del Sur y Sandwich del Sur'),
    ('HMD', 'Islas Heard y McDonald'),
    ('MDV', 'Islas Maldivas'),
    ('FLK', 'Islas Malvinas'),
    ('MNP', 'Islas Marianas del Norte'),
    ('MHL', 'Islas Marshall'),
    ('PCN', 'Islas Pitcairn'),
    ('SLB', 'Islas Salomón'),
    ('TCA', 'Islas Turcas y Caicos'),
    ('UMI', 'Islas Ultramarinas Menores de Estados Unidos'),
    ('VG', 'Islas Vígenes Británicas'),
    ('VIR', 'Islas Vírgenes de los Estados Unidos'),
    ('ISR', 'Israel'),
    ('ITA', 'Italia'),
    ('JAM', 'Jamaica'),
    ('JPN', 'Japón'),
    ('JEY', 'Jersey'),
    ('JOR', 'Jordania'),
    ('KAZ', 'Kazajistán'),
    ('KEN', 'Kenia'),
    ('KGZ', 'Kirgizstán'),
    ('KIR', 'Kiribati'),
    ('KWT', 'Kuwait'),
    ('LBN', 'Líbano'),
    ('LAO', 'Laos'),
    ('LSO', 'Lesoto'),
    ('LVA', 'Letonia'),
    ('LBR', 'Liberia'),
    ('LBY', 'Libia'),
    ('LIE', 'Liechtenstein'),
    ('LTU', 'Lituania'),
    ('LUX', 'Luxemburgo'),
    ('MEX', 'México'),
    ('MCO', 'Mónaco'),
    ('MAC', 'Macao'),
    ('MKD', 'Macedonia'),
    ('MDG', 'Madagascar'),
    ('MYS', 'Malasia'),
    ('MWI', 'Malawi'),
    ('MLI', 'Mali'),
    ('MLT', 'Malta'),
    ('MAR', 'Marruecos'),
    ('MTQ', 'Martinica'),
    ('MUS', 'Mauricio'),
    ('MRT', 'Mauritania'),
    ('MYT', 'Mayotte'),
    ('FSM', 'Micronesia'),
    ('MDA', 'Moldavia'),
    ('MNG', 'Mongolia'),
    ('MNE', 'Montenegro'),
    ('MSR', 'Montserrat'),
    ('MOZ', 'Mozambique'),
    ('NAM', 'Namibia'),
    ('NRU', 'Nauru'),
    ('NPL', 'Nepal'),
    ('NIC', 'Nicaragua'),
    ('NER', 'Niger'),
    ('NGA', 'Nigeria'),
    ('NIU', 'Niue'),
    ('NOR', 'Noruega'),
    ('NCL', 'Nueva Caledonia'),
    ('NZL', 'Nueva Zelanda'),
    ('OMN', 'Omán'),
    ('NLD', 'Paises Bajos'),
    ('PAK', 'Pakistan'),
    ('PLW', 'Palau'),
    ('PSE', 'Palestina'),
    ('PAN', 'Panama'),
    ('PNG', 'Papua Nueva Guinea'),
    ('PRY', 'Paraguay'),
    ('PER', 'Perú'),
    ('PYF', 'Polinesia Francesa'),
    ('POL', 'Polonia'),
    ('PRT', 'Portugal'),
    ('PRI', 'Puerto Rico'),
    ('QAT', 'Qatar'),
    ('GBR', 'Reino Unido'),
    ('CAF', 'República Centroafricana'),
    ('CZE', 'República Checa'),
    ('DOM', 'República Dominicana'),
    ('REU', 'Reunin'),
    ('RWA', 'Ruanda'),
    ('ROU', 'Rumania'),
    ('RUS', 'Rusia'),
    ('ESH', 'Sahara Occidental'),
    ('WSM', 'Samoa'),
    ('ASM', 'Samoa Americana'),
    ('BLM', 'San Bartolomé'),
    ('KNA', 'San Cristobal y Nieves'),
    ('SMR', 'San Marino'),
    ('MAF', 'San Martin (Francia)'),
    ('SPM', 'San Pedro y Miquelón'),
    ('VCT', 'San Vicente y las Granadinas'),
    ('SHN', 'Santa Elena'),
    ('LCA', 'Santa Lucía'),
    ('STP', 'Santo Tomé  y Príncipe'),
    ('SEN', 'Senegal'),
    ('SRB', 'Serbia'),
    ('SYC', 'Seychelles'),
    ('SLE', 'Sierra Leona'),
    ('SGP', 'Singapur'),
    ('SYR', 'Siria'),
    ('SOM', 'Somalia'),
    ('LKA', 'Sri lanka'),
    ('ZAF', 'Sudáfrica'),
    ('SDN', 'Sudán'),
    ('SWE', 'Suecia'),
    ('CHE', 'Suiza'),
    ('SUR', 'Suriname'),
    ('SJM', 'Svalbard y Jan Mayen'),
    ('SWZ', 'Swazilandia'),
    ('TJK', 'Tadjikistán'),
    ('THA', 'Tailandia'),
    ('TWN', 'Taiwan'),
    ('TZA', 'Tanzania'),
    ('IOT', 'Territorio Brita1nico del Oceano Indico'),
    ('ATF', 'Territorios Australes y Antarticas Franceses'),
    ('TLS', 'Timor Oriental'),
    ('TGO', 'Togo'),
    ('TKL', 'Tokelau'),
    ('TON', 'Tonga'),
    ('TTO', 'Trinidad y Tobago'),
    ('TUN', 'Tunez'),
    ('TKM', 'Turkmenistan'),
    ('TUR', 'Turquía'),
    ('TUV', 'Tuvalu'),
    ('UKR', 'Ucrania'),
    ('UGA', 'Uganda'),
    ('URY', 'Uruguay'),
    ('UZB', 'Uzbekistan'),
    ('VUT', 'Vanuatu'),
    ('VEN', 'Venezuela'),
    ('VNM', 'Vietnam'),
    ('WLF', 'Wallis y Futuna'),
    ('YEM', 'Yemen'),
    ('DJI', 'Yibuti'),
    ('ZMB', 'Zambia'),
    ('ZWE', 'Zimbabue'),
)


CHOICES_FOR_PAISES_FILTER = [
    ('', 'Por favor seleccione un pais'),
]
CHOICES_FOR_PAISES_FILTER.extend(list(PAISES_CHOICES))
