# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-01 16:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cancha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('deporte', models.CharField(blank=True, choices=[(b'Futbol', b'Futbol'), (b'Basquet', b'Basquet'), (b'Paddle', b'Paddle'), (b'Tenis', b'Tenis')], max_length=100, null=True)),
                ('superficie', models.CharField(blank=True, choices=[(b'Cesped Natural', b'Cesped Natural'), (b'Cesped Sintetico', b'Cesped Sintetico'), (b'Polvo de Ladrillo', b'Polvo de Ladrillo'), (b'Cemento', b'Cemento')], max_length=100, null=True)),
                ('techada', models.BooleanField(default=False)),
                ('luz', models.BooleanField(default=False)),
                ('descripcion', models.TextField(blank=True, max_length=500, null=True)),
                ('precio_sin_luz', models.IntegerField(default=0)),
                ('precio_con_luz', models.IntegerField(default=0)),
                ('lunes', models.BooleanField(default=False)),
                ('lunes_doble_turno', models.BooleanField(default=False)),
                ('desde_lunes', models.TimeField(blank=True, null=True)),
                ('hasta_lunes', models.TimeField(blank=True, null=True)),
                ('desde_lunes_tarde', models.TimeField(blank=True, null=True)),
                ('hasta_lunes_tarde', models.TimeField(blank=True, null=True)),
                ('martes', models.BooleanField(default=False)),
                ('martes_doble_turno', models.BooleanField(default=False)),
                ('hasta_martes', models.TimeField(blank=True, null=True)),
                ('desde_martes_tarde', models.TimeField(blank=True, null=True)),
                ('hasta_martes_tarde', models.TimeField(blank=True, null=True)),
                ('miercoles', models.BooleanField(default=False)),
                ('miercoles_doble_turno', models.BooleanField(default=False)),
                ('desde_miercoles', models.TimeField(blank=True, null=True)),
                ('hasta_miercoles', models.TimeField(blank=True, null=True)),
                ('desde_miercoles_tarde', models.TimeField(blank=True, null=True)),
                ('hasta_miercoles_tarde', models.TimeField(blank=True, null=True)),
                ('jueves', models.BooleanField(default=False)),
                ('jueves_doble_turno', models.BooleanField(default=False)),
                ('desde_jueves', models.TimeField(blank=True, null=True)),
                ('hasta_jueves', models.TimeField(blank=True, null=True)),
                ('desde_jueves_tarde', models.TimeField(blank=True, null=True)),
                ('hasta_jueves_tarde', models.TimeField(blank=True, null=True)),
                ('viernes', models.BooleanField(default=False)),
                ('viernes_doble_turno', models.BooleanField(default=False)),
                ('desde_viernes', models.TimeField(blank=True, null=True)),
                ('hasta_viernes', models.TimeField(blank=True, null=True)),
                ('desde_viernes_tarde', models.TimeField(blank=True, null=True)),
                ('hasta_viernes_tarde', models.TimeField(blank=True, null=True)),
                ('sabado', models.BooleanField(default=False)),
                ('sabado_doble_turno', models.BooleanField(default=False)),
                ('desde_sabado', models.TimeField(blank=True, null=True)),
                ('hasta_sabado', models.TimeField(blank=True, null=True)),
                ('desde_sabado_tarde', models.TimeField(blank=True, null=True)),
                ('hasta_sabado_tarde', models.TimeField(blank=True, null=True)),
                ('domingo', models.BooleanField(default=False)),
                ('domingo_doble_turno', models.BooleanField(default=False)),
                ('desde_domingo', models.TimeField(blank=True, null=True)),
                ('hasta_domingo', models.TimeField(blank=True, null=True)),
                ('desde_domingo_tarde', models.TimeField(blank=True, null=True)),
                ('hasta_domingo_tarde', models.TimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmpleadoEstablecimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Establecimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('pais', models.CharField(choices=[(b'AFG', b'Afganistan'), (b'ALB', b'Albania'), (b'DEU', b'Alemania'), (b'DZA', b'Algeria'), (b'AND', b'Andorra'), (b'AGO', b'Angola'), (b'AIA', b'Anguila'), (b'ATA', b'Antartida'), (b'ATG', b'Antigua y Barbuda'), (b'ANT', b'Antillas Neerlandesas'), (b'SAU', b'Arabia Saudita'), (b'ARG', b'Argentina'), (b'ARM', b'Armenia'), (b'ABW', b'Aruba'), (b'AUS', b'Australia'), (b'AUT', b'Austria'), (b'AZE', b'Azerbayan'), (b'BEL', b'Belgica'), (b'BHS', b'Bahamas'), (b'BHR', b'Bahrein'), (b'BGD', b'Bangladesh'), (b'BRB', b'Barbados'), (b'BLZ', b'Belice'), (b'BEN', b'Benadn'), (b'BTN', b'Bhutan'), (b'BLR', b'Bielorrusia'), (b'MMR', b'Birmania'), (b'BOL', b'Bolivia'), (b'BIH', b'Bosnia y Herzegovina'), (b'BWA', b'Botsuana'), (b'BRA', b'Brasil'), (b'BRN', b'Brunei'), (b'BGR', b'Bulgaria'), (b'BFA', b'Burkina Faso'), (b'BDI', b'Burundi'), (b'CPV', b'Cabo Verde'), (b'KHM', b'Camboya'), (b'CMR', b'Camerun'), (b'CAN', b'Canada'), (b'TCD', b'Chad'), (b'CHL', b'Chile'), (b'CHN', b'China'), (b'CYP', b'Chipre'), (b'VAT', b'Ciudad del Vaticano'), (b'COL', b'Colombia'), (b'COM', b'Comoras'), (b'COG', b'Congo'), (b'COD', b'Congo'), (b'PRK', b'Corea del Norte'), (b'KOR', b'Corea del Sur'), (b'CIV', b'Costa de Marfil'), (b'CRI', b'Costa Rica'), (b'HRV', b'Croacia'), (b'CUB', b'Cuba'), (b'DNK', b'Dinamarca'), (b'DMA', b'Dominica'), (b'ECU', b'Ecuador'), (b'EGY', b'Egipto'), (b'SLV', b'El Salvador'), (b'ARE', b'Emiratos Arabes Unidos'), (b'ERI', b'Eritrea'), (b'SVK', b'Eslovaquia'), (b'SVN', b'Eslovenia'), (b'ESP', b'Espa\xc3\xb1a'), (b'USA', b'Estados Unidos de America'), (b'EST', b'Estonia'), (b'ETH', b'Etiopia'), (b'PHL', b'Filipinas'), (b'FIN', b'Finlandia'), (b'FJI', b'Fiyi'), (b'FRA', b'Francia'), (b'GAB', b'Gabon'), (b'GMB', b'Gambia'), (b'GEO', b'Georgia'), (b'GHA', b'Ghana'), (b'GIB', b'Gibraltar'), (b'GRD', b'Granada'), (b'GRC', b'Grecia'), (b'GRL', b'Groenlandia'), (b'GLP', b'Guadalupe'), (b'GUM', b'Guam'), (b'GTM', b'Guatemala'), (b'GUF', b'Guayana Francesa'), (b'GGY', b'Guernsey'), (b'GIN', b'Guinea'), (b'GNQ', b'Guinea Ecuatorial'), (b'GNB', b'Guinea-Bissau'), (b'GUY', b'Guyana'), (b'HTI', b'Haiti'), (b'HND', b'Honduras'), (b'HKG', b'Hong kong'), (b'HUN', b'Hungr\xc3\xada'), (b'IND', b'India'), (b'IDN', b'Indonesia'), (b'IRN', b'Ir\xc3\xa1n'), (b'IRQ', b'Irak'), (b'IRL', b'Irlanda'), (b'BVT', b'Isla Bouvet'), (b'IMN', b'Isla de Man'), (b'CXR', b'Isla de Navidad'), (b'NFK', b'Isla Norfolk'), (b'ISL', b'Islandia'), (b'BMU', b'Islas Bermudas'), (b'CYM', b'Islas Caim\xc3\xa1n'), (b'CCK', b'Islas Cocos (Keeling)'), (b'COK', b'Islas Cook'), (b'ALA', b'Islas de Aland'), (b'FRO', b'Islas Feroe'), (b'SGS', b'Islas Georgias del Sur y Sandwich del Sur'), (b'HMD', b'Islas Heard y McDonald'), (b'MDV', b'Islas Maldivas'), (b'FLK', b'Islas Malvinas'), (b'MNP', b'Islas Marianas del Norte'), (b'MHL', b'Islas Marshall'), (b'PCN', b'Islas Pitcairn'), (b'SLB', b'Islas Salom\xc3\xb3n'), (b'TCA', b'Islas Turcas y Caicos'), (b'UMI', b'Islas Ultramarinas Menores de Estados Unidos'), (b'VG', b'Islas V\xc3\xadgenes Brit\xc3\xa1nicas'), (b'VIR', b'Islas V\xc3\xadrgenes de los Estados Unidos'), (b'ISR', b'Israel'), (b'ITA', b'Italia'), (b'JAM', b'Jamaica'), (b'JPN', b'Jap\xc3\xb3n'), (b'JEY', b'Jersey'), (b'JOR', b'Jordania'), (b'KAZ', b'Kazajist\xc3\xa1n'), (b'KEN', b'Kenia'), (b'KGZ', b'Kirgizst\xc3\xa1n'), (b'KIR', b'Kiribati'), (b'KWT', b'Kuwait'), (b'LBN', b'L\xc3\xadbano'), (b'LAO', b'Laos'), (b'LSO', b'Lesoto'), (b'LVA', b'Letonia'), (b'LBR', b'Liberia'), (b'LBY', b'Libia'), (b'LIE', b'Liechtenstein'), (b'LTU', b'Lituania'), (b'LUX', b'Luxemburgo'), (b'MEX', b'M\xc3\xa9xico'), (b'MCO', b'M\xc3\xb3naco'), (b'MAC', b'Macao'), (b'MKD', b'Macedonia'), (b'MDG', b'Madagascar'), (b'MYS', b'Malasia'), (b'MWI', b'Malawi'), (b'MLI', b'Mali'), (b'MLT', b'Malta'), (b'MAR', b'Marruecos'), (b'MTQ', b'Martinica'), (b'MUS', b'Mauricio'), (b'MRT', b'Mauritania'), (b'MYT', b'Mayotte'), (b'FSM', b'Micronesia'), (b'MDA', b'Moldavia'), (b'MNG', b'Mongolia'), (b'MNE', b'Montenegro'), (b'MSR', b'Montserrat'), (b'MOZ', b'Mozambique'), (b'NAM', b'Namibia'), (b'NRU', b'Nauru'), (b'NPL', b'Nepal'), (b'NIC', b'Nicaragua'), (b'NER', b'Niger'), (b'NGA', b'Nigeria'), (b'NIU', b'Niue'), (b'NOR', b'Noruega'), (b'NCL', b'Nueva Caledonia'), (b'NZL', b'Nueva Zelanda'), (b'OMN', b'Om\xc3\xa1n'), (b'NLD', b'Paises Bajos'), (b'PAK', b'Pakistan'), (b'PLW', b'Palau'), (b'PSE', b'Palestina'), (b'PAN', b'Panama'), (b'PNG', b'Papua Nueva Guinea'), (b'PRY', b'Paraguay'), (b'PER', b'Per\xc3\xba'), (b'PYF', b'Polinesia Francesa'), (b'POL', b'Polonia'), (b'PRT', b'Portugal'), (b'PRI', b'Puerto Rico'), (b'QAT', b'Qatar'), (b'GBR', b'Reino Unido'), (b'CAF', b'Rep\xc3\xbablica Centroafricana'), (b'CZE', b'Rep\xc3\xbablica Checa'), (b'DOM', b'Rep\xc3\xbablica Dominicana'), (b'REU', b'Reunin'), (b'RWA', b'Ruanda'), (b'ROU', b'Rumania'), (b'RUS', b'Rusia'), (b'ESH', b'Sahara Occidental'), (b'WSM', b'Samoa'), (b'ASM', b'Samoa Americana'), (b'BLM', b'San Bartolom\xc3\xa9'), (b'KNA', b'San Cristobal y Nieves'), (b'SMR', b'San Marino'), (b'MAF', b'San Martin (Francia)'), (b'SPM', b'San Pedro y Miquel\xc3\xb3n'), (b'VCT', b'San Vicente y las Granadinas'), (b'SHN', b'Santa Elena'), (b'LCA', b'Santa Luc\xc3\xada'), (b'STP', b'Santo Tom\xc3\xa9  y Pr\xc3\xadncipe'), (b'SEN', b'Senegal'), (b'SRB', b'Serbia'), (b'SYC', b'Seychelles'), (b'SLE', b'Sierra Leona'), (b'SGP', b'Singapur'), (b'SYR', b'Siria'), (b'SOM', b'Somalia'), (b'LKA', b'Sri lanka'), (b'ZAF', b'Sud\xc3\xa1frica'), (b'SDN', b'Sud\xc3\xa1n'), (b'SWE', b'Suecia'), (b'CHE', b'Suiza'), (b'SUR', b'Suriname'), (b'SJM', b'Svalbard y Jan Mayen'), (b'SWZ', b'Swazilandia'), (b'TJK', b'Tadjikist\xc3\xa1n'), (b'THA', b'Tailandia'), (b'TWN', b'Taiwan'), (b'TZA', b'Tanzania'), (b'IOT', b'Territorio Brita1nico del Oceano Indico'), (b'ATF', b'Territorios Australes y Antarticas Franceses'), (b'TLS', b'Timor Oriental'), (b'TGO', b'Togo'), (b'TKL', b'Tokelau'), (b'TON', b'Tonga'), (b'TTO', b'Trinidad y Tobago'), (b'TUN', b'Tunez'), (b'TKM', b'Turkmenistan'), (b'TUR', b'Turqu\xc3\xada'), (b'TUV', b'Tuvalu'), (b'UKR', b'Ucrania'), (b'UGA', b'Uganda'), (b'URY', b'Uruguay'), (b'UZB', b'Uzbekistan'), (b'VUT', b'Vanuatu'), (b'VEN', b'Venezuela'), (b'VNM', b'Vietnam'), (b'WLF', b'Wallis y Futuna'), (b'YEM', b'Yemen'), (b'DJI', b'Yibuti'), (b'ZMB', b'Zambia'), (b'ZWE', b'Zimbabue')], default='ARG', max_length=100)),
                ('provincia', models.CharField(default='', max_length=100)),
                ('localidad', models.CharField(default='', max_length=100)),
                ('direccion', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, max_length=500, null=True)),
                ('vestuario', models.BooleanField(default=False)),
                ('asador', models.BooleanField(default=False)),
                ('estacionamiento', models.BooleanField(default=False)),
                ('duchas', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Favorito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cancha', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favoritos', to='canchas.Cancha')),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='establecimientos/', verbose_name='Image')),
                ('establecimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='canchas.Establecimiento')),
            ],
        ),
        migrations.CreateModel(
            name='ImagesCancha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='canchas/', verbose_name='Image')),
                ('cancha', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='canchas.Cancha')),
            ],
        ),
        migrations.CreateModel(
            name='OwnerEstablecimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dueno', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmada', models.BooleanField(default=False)),
                ('cancelada', models.BooleanField(default=False)),
                ('pendiente', models.BooleanField(default=True)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('horario_inicio', models.TimeField(blank=True, null=True)),
                ('horario_fin', models.TimeField(blank=True, null=True)),
                ('con_luz', models.BooleanField(default=False)),
                ('asistio', models.BooleanField(default=False)),
                ('cancha', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='canchas.Cancha')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('cod_tel', models.CharField(blank=True, max_length=10, null=True)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='reserva',
            name='creador_de_reserva',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='canchas.UserProfile'),
        ),
        migrations.AddField(
            model_name='favorito',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favoritos', to='canchas.UserProfile'),
        ),
        migrations.AddField(
            model_name='establecimiento',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='establecimientos', to='canchas.OwnerEstablecimiento'),
        ),
        migrations.AddField(
            model_name='empleadoestablecimiento',
            name='empleador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empleados', to='canchas.OwnerEstablecimiento'),
        ),
        migrations.AddField(
            model_name='empleadoestablecimiento',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='empleado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cancha',
            name='establecimiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='canchas', to='canchas.Establecimiento'),
        ),
    ]
