# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-03-17 19:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canchas', '0002_cancha_desde_martes'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'pendiente'), ('confirmada', 'confirmada'), ('vencida', 'vencida'), ('cancelada', 'cancelada')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reserva',
            name='mp_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ID Transacción de Mercadopago'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='mp_pendiente',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reserva',
            name='mp_url',
            field=models.CharField(default='', help_text='Puede copiar esta dirección para enviar por email u otro medio', max_length=255, verbose_name='Dirección p/Pago'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='uuid',
            field=models.CharField(editable=False, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='cancha',
            name='deporte',
            field=models.CharField(blank=True, choices=[('Futbol', 'Futbol'), ('Basquet', 'Basquet'), ('Paddle', 'Paddle'), ('Tenis', 'Tenis')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cancha',
            name='superficie',
            field=models.CharField(blank=True, choices=[('Cesped Natural', 'Cesped Natural'), ('Cesped Sintetico', 'Cesped Sintetico'), ('Polvo de Ladrillo', 'Polvo de Ladrillo'), ('Cemento', 'Cemento')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='establecimiento',
            name='pais',
            field=models.CharField(choices=[('AFG', 'Afganistan'), ('ALB', 'Albania'), ('DEU', 'Alemania'), ('DZA', 'Algeria'), ('AND', 'Andorra'), ('AGO', 'Angola'), ('AIA', 'Anguila'), ('ATA', 'Antartida'), ('ATG', 'Antigua y Barbuda'), ('ANT', 'Antillas Neerlandesas'), ('SAU', 'Arabia Saudita'), ('ARG', 'Argentina'), ('ARM', 'Armenia'), ('ABW', 'Aruba'), ('AUS', 'Australia'), ('AUT', 'Austria'), ('AZE', 'Azerbayan'), ('BEL', 'Belgica'), ('BHS', 'Bahamas'), ('BHR', 'Bahrein'), ('BGD', 'Bangladesh'), ('BRB', 'Barbados'), ('BLZ', 'Belice'), ('BEN', 'Benadn'), ('BTN', 'Bhutan'), ('BLR', 'Bielorrusia'), ('MMR', 'Birmania'), ('BOL', 'Bolivia'), ('BIH', 'Bosnia y Herzegovina'), ('BWA', 'Botsuana'), ('BRA', 'Brasil'), ('BRN', 'Brunei'), ('BGR', 'Bulgaria'), ('BFA', 'Burkina Faso'), ('BDI', 'Burundi'), ('CPV', 'Cabo Verde'), ('KHM', 'Camboya'), ('CMR', 'Camerun'), ('CAN', 'Canada'), ('TCD', 'Chad'), ('CHL', 'Chile'), ('CHN', 'China'), ('CYP', 'Chipre'), ('VAT', 'Ciudad del Vaticano'), ('COL', 'Colombia'), ('COM', 'Comoras'), ('COG', 'Congo'), ('COD', 'Congo'), ('PRK', 'Corea del Norte'), ('KOR', 'Corea del Sur'), ('CIV', 'Costa de Marfil'), ('CRI', 'Costa Rica'), ('HRV', 'Croacia'), ('CUB', 'Cuba'), ('DNK', 'Dinamarca'), ('DMA', 'Dominica'), ('ECU', 'Ecuador'), ('EGY', 'Egipto'), ('SLV', 'El Salvador'), ('ARE', 'Emiratos Arabes Unidos'), ('ERI', 'Eritrea'), ('SVK', 'Eslovaquia'), ('SVN', 'Eslovenia'), ('ESP', 'España'), ('USA', 'Estados Unidos de America'), ('EST', 'Estonia'), ('ETH', 'Etiopia'), ('PHL', 'Filipinas'), ('FIN', 'Finlandia'), ('FJI', 'Fiyi'), ('FRA', 'Francia'), ('GAB', 'Gabon'), ('GMB', 'Gambia'), ('GEO', 'Georgia'), ('GHA', 'Ghana'), ('GIB', 'Gibraltar'), ('GRD', 'Granada'), ('GRC', 'Grecia'), ('GRL', 'Groenlandia'), ('GLP', 'Guadalupe'), ('GUM', 'Guam'), ('GTM', 'Guatemala'), ('GUF', 'Guayana Francesa'), ('GGY', 'Guernsey'), ('GIN', 'Guinea'), ('GNQ', 'Guinea Ecuatorial'), ('GNB', 'Guinea-Bissau'), ('GUY', 'Guyana'), ('HTI', 'Haiti'), ('HND', 'Honduras'), ('HKG', 'Hong kong'), ('HUN', 'Hungría'), ('IND', 'India'), ('IDN', 'Indonesia'), ('IRN', 'Irán'), ('IRQ', 'Irak'), ('IRL', 'Irlanda'), ('BVT', 'Isla Bouvet'), ('IMN', 'Isla de Man'), ('CXR', 'Isla de Navidad'), ('NFK', 'Isla Norfolk'), ('ISL', 'Islandia'), ('BMU', 'Islas Bermudas'), ('CYM', 'Islas Caimán'), ('CCK', 'Islas Cocos (Keeling)'), ('COK', 'Islas Cook'), ('ALA', 'Islas de Aland'), ('FRO', 'Islas Feroe'), ('SGS', 'Islas Georgias del Sur y Sandwich del Sur'), ('HMD', 'Islas Heard y McDonald'), ('MDV', 'Islas Maldivas'), ('FLK', 'Islas Malvinas'), ('MNP', 'Islas Marianas del Norte'), ('MHL', 'Islas Marshall'), ('PCN', 'Islas Pitcairn'), ('SLB', 'Islas Salomón'), ('TCA', 'Islas Turcas y Caicos'), ('UMI', 'Islas Ultramarinas Menores de Estados Unidos'), ('VG', 'Islas Vígenes Británicas'), ('VIR', 'Islas Vírgenes de los Estados Unidos'), ('ISR', 'Israel'), ('ITA', 'Italia'), ('JAM', 'Jamaica'), ('JPN', 'Japón'), ('JEY', 'Jersey'), ('JOR', 'Jordania'), ('KAZ', 'Kazajistán'), ('KEN', 'Kenia'), ('KGZ', 'Kirgizstán'), ('KIR', 'Kiribati'), ('KWT', 'Kuwait'), ('LBN', 'Líbano'), ('LAO', 'Laos'), ('LSO', 'Lesoto'), ('LVA', 'Letonia'), ('LBR', 'Liberia'), ('LBY', 'Libia'), ('LIE', 'Liechtenstein'), ('LTU', 'Lituania'), ('LUX', 'Luxemburgo'), ('MEX', 'México'), ('MCO', 'Mónaco'), ('MAC', 'Macao'), ('MKD', 'Macedonia'), ('MDG', 'Madagascar'), ('MYS', 'Malasia'), ('MWI', 'Malawi'), ('MLI', 'Mali'), ('MLT', 'Malta'), ('MAR', 'Marruecos'), ('MTQ', 'Martinica'), ('MUS', 'Mauricio'), ('MRT', 'Mauritania'), ('MYT', 'Mayotte'), ('FSM', 'Micronesia'), ('MDA', 'Moldavia'), ('MNG', 'Mongolia'), ('MNE', 'Montenegro'), ('MSR', 'Montserrat'), ('MOZ', 'Mozambique'), ('NAM', 'Namibia'), ('NRU', 'Nauru'), ('NPL', 'Nepal'), ('NIC', 'Nicaragua'), ('NER', 'Niger'), ('NGA', 'Nigeria'), ('NIU', 'Niue'), ('NOR', 'Noruega'), ('NCL', 'Nueva Caledonia'), ('NZL', 'Nueva Zelanda'), ('OMN', 'Omán'), ('NLD', 'Paises Bajos'), ('PAK', 'Pakistan'), ('PLW', 'Palau'), ('PSE', 'Palestina'), ('PAN', 'Panama'), ('PNG', 'Papua Nueva Guinea'), ('PRY', 'Paraguay'), ('PER', 'Perú'), ('PYF', 'Polinesia Francesa'), ('POL', 'Polonia'), ('PRT', 'Portugal'), ('PRI', 'Puerto Rico'), ('QAT', 'Qatar'), ('GBR', 'Reino Unido'), ('CAF', 'República Centroafricana'), ('CZE', 'República Checa'), ('DOM', 'República Dominicana'), ('REU', 'Reunin'), ('RWA', 'Ruanda'), ('ROU', 'Rumania'), ('RUS', 'Rusia'), ('ESH', 'Sahara Occidental'), ('WSM', 'Samoa'), ('ASM', 'Samoa Americana'), ('BLM', 'San Bartolomé'), ('KNA', 'San Cristobal y Nieves'), ('SMR', 'San Marino'), ('MAF', 'San Martin (Francia)'), ('SPM', 'San Pedro y Miquelón'), ('VCT', 'San Vicente y las Granadinas'), ('SHN', 'Santa Elena'), ('LCA', 'Santa Lucía'), ('STP', 'Santo Tomé  y Príncipe'), ('SEN', 'Senegal'), ('SRB', 'Serbia'), ('SYC', 'Seychelles'), ('SLE', 'Sierra Leona'), ('SGP', 'Singapur'), ('SYR', 'Siria'), ('SOM', 'Somalia'), ('LKA', 'Sri lanka'), ('ZAF', 'Sudáfrica'), ('SDN', 'Sudán'), ('SWE', 'Suecia'), ('CHE', 'Suiza'), ('SUR', 'Suriname'), ('SJM', 'Svalbard y Jan Mayen'), ('SWZ', 'Swazilandia'), ('TJK', 'Tadjikistán'), ('THA', 'Tailandia'), ('TWN', 'Taiwan'), ('TZA', 'Tanzania'), ('IOT', 'Territorio Brita1nico del Oceano Indico'), ('ATF', 'Territorios Australes y Antarticas Franceses'), ('TLS', 'Timor Oriental'), ('TGO', 'Togo'), ('TKL', 'Tokelau'), ('TON', 'Tonga'), ('TTO', 'Trinidad y Tobago'), ('TUN', 'Tunez'), ('TKM', 'Turkmenistan'), ('TUR', 'Turquía'), ('TUV', 'Tuvalu'), ('UKR', 'Ucrania'), ('UGA', 'Uganda'), ('URY', 'Uruguay'), ('UZB', 'Uzbekistan'), ('VUT', 'Vanuatu'), ('VEN', 'Venezuela'), ('VNM', 'Vietnam'), ('WLF', 'Wallis y Futuna'), ('YEM', 'Yemen'), ('DJI', 'Yibuti'), ('ZMB', 'Zambia'), ('ZWE', 'Zimbabue')], default='ARG', max_length=100),
        ),
    ]
