# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-03-17 20:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canchas', '0003_auto_20200317_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'pendiente'), ('confirmada', 'confirmada'), ('vencida', 'vencida'), ('cancelada', 'cancelada')], default='pendiente', max_length=50),
        ),
    ]
