# Generated by Django 5.1.1 on 2024-10-05 22:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canchas', '0004_auto_20200317_2009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='horario_fin',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='horario_inicio',
        ),
        migrations.AddField(
            model_name='cancha',
            name='comision',
            field=models.DecimalField(decimal_places=2, default=0.1, max_digits=9),
        ),
        migrations.AddField(
            model_name='establecimiento',
            name='direccion_lat',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='establecimiento',
            name='direccion_lng',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='cancelada_por_cliente',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='reserva',
            name='deposito_reserva',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
        migrations.AddField(
            model_name='reserva',
            name='periodo',
            field=models.CharField(choices=[('0:00Hs a 1:00Hs', '0:00Hs a 1:00Hs'), ('1:00Hs a 2:00Hs', '1:00Hs a 2:00Hs'), ('2:00Hs a 3:00Hs', '2:00Hs a 3:00Hs'), ('3:00Hs a 4:00Hs', '3:00Hs a 4:00Hs'), ('4:00Hs a 5:00Hs', '4:00Hs a 5:00Hs'), ('5:00Hs a 6:00Hs', '5:00Hs a 6:00Hs'), ('6:00Hs a 7:00Hs', '6:00Hs a 7:00Hs'), ('7:00Hs a 8:00Hs', '7:00Hs a 8:00Hs'), ('8:00Hs a 9:00Hs', '8:00Hs a 9:00Hs'), ('9:00Hs a 10:00Hs', '9:00Hs a 10:00Hs'), ('10:00Hs a 11:00Hs', '10:00Hs a 11:00Hs'), ('11:00Hs a 12:00Hs', '11:00Hs a 12:00Hs'), ('12:00Hs a 13:00Hs', '12:00Hs a 13:00Hs'), ('13:00Hs a 14:00Hs', '13:00Hs a 14:00Hs'), ('14:00Hs a 15:00Hs', '14:00Hs a 15:00Hs'), ('15:00Hs a 16:00Hs', '15:00Hs a 16:00Hs'), ('16:00Hs a 17:00Hs', '16:00Hs a 17:00Hs'), ('17:00Hs a 18:00Hs', '17:00Hs a 18:00Hs'), ('18:00Hs a 19:00Hs', '18:00Hs a 19:00Hs'), ('19:00Hs a 20:00Hs', '19:00Hs a 20:00Hs'), ('20:00Hs a 21:00Hs', '20:00Hs a 21:00Hs'), ('21:00Hs a 22:00Hs', '21:00Hs a 22:00Hs'), ('22:00Hs a 23:00Hs', '22:00Hs a 23:00Hs'), ('23:00Hs a 24:00Hs', '23:00Hs a 24:00Hs')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='retiro',
            field=models.CharField(choices=[('A liquidar', 'A liquidar'), ('Pagado', 'Pagado'), ('A Revisar', 'A revisar')], default='A liquidar', max_length=20),
        ),
        migrations.AddField(
            model_name='reserva',
            name='saldo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='cancha',
            name='precio_con_luz',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='cancha',
            name='superficie',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='favorito',
            name='cancha',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='favoritos', to='canchas.cancha'),
        ),
        migrations.AlterField(
            model_name='favorito',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='favoritos', to='canchas.userprofile'),
        ),
        migrations.AlterField(
            model_name='imagescancha',
            name='cancha',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='canchas.cancha'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='cancha',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservas', to='canchas.cancha'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='creador_de_reserva',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservas', to='canchas.userprofile'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'pendiente'), ('acreditada', 'acreditada'), ('vencida', 'vencida'), ('cancelada', 'cancelada'), ('reintegrada', 'reintegrada')], default='pendiente', max_length=50),
        ),
        migrations.CreateModel(
            name='Facturacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo_de_pago', models.CharField(blank=True, choices=[('CBU', 'CBU'), ('Mercado Pago', 'Mercado Pago')], max_length=100, null=True)),
                ('cbu', models.CharField(blank=True, max_length=22, null=True)),
                ('mercadopago', models.CharField(blank=True, max_length=100, null=True)),
                ('establecimiento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='facturacion', to='canchas.establecimiento')),
            ],
        ),
    ]
