# Generated by Django 5.1.1 on 2024-10-12 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canchas', '0006_alter_cancha_id_alter_empleadoestablecimiento_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownerestablecimiento',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
